[project]
name = "transition-energetique-regionale"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cebdewaelle", email = "sdewaelle@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
transition-energetique-regionale = "transition_energetique_regionale:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.19.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
