name: CI

on:
  push:
  pull_request:
    branches: [main,develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v7

      - name: Installer uv
        uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true

      - name: Installer les dépendances
        run: uv sync --locked

      - name: Lancer les tests
        run: uv run pytest